# This configuration was used Ebert to review the ItsJuice/juicebox repository
# on 6ec38a0246d0ae9f32e117429fee177b118deca8.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://ebertapp.io/docs/config and see the configuration
# details.
---
styleguide: littleowllabs/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- config
- test

