language: elixir
elixir:
  - 1.3.1
env:
  global:
    - WEBDRIVER=phantomjs
before_install:
  - nvm install 6.3.1
  - npm install -g yarn
before_script:
  - npm install
  - bash $TRAVIS_BUILD_DIR/test/tools/start_webdriver.sh
script:
  - mix test
  - npm test
